pipeline {
    agent any
        environment{
        DOCKERHUB_CREDENCIALS = credentials ('dockerhub')
        RepoDockerHub = 'zdenkoo98'
        NameContainer = 'pokedex-flask'
    }
    stage('Login to Dockerhub'){
        steps{
                sh "echo $DOCKERHUB_CREDENCIALS_PSW | docker login -u $DOCKERHUB_CREDENCIALS_USR --password-stdin "
            }
        }


    stages {
        stage('Build'){
            steps{
                sh "docker build -t zdenkoo98/pokedex-flask:${env.BUILD_NUMBER} ."
            }
        }
    }
}
