pipeline {
    agent any
        environment{
        DOCKERHUB_CREDENCIALS = credentials ('dockerhub')
        RepoDockerHub = 'zdenkoo98'
        NameContainer = 'pokedex-flask'
    }

    stages {
        stage('Build'){
            steps{
                sh "docker build -t zdenkoo98/pokedex-flask:${env.BUILD_NUMBER} ."
            }
        }
    }
}
